import dynamic from 'next/dynamic'
import './globals.css'
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false;

const LayoutContainer = dynamic(() => import('./LayoutContanier'), {
  ssr : false
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir='rtl'>
      <body 
      >
       <LayoutContainer>
         {children}
       </LayoutContainer>
       
      </body>
    </html>
  )
}
